### ISSUE TITLE
Exception undefined local variable or method `address_type'

### ISSUE THREAD

**Issue by meltzow** [spree-contrib/spree_address_book#45]
Hi,

after I upgrade my spree to 1.2.3 I get an exception: 
app/views/spree/addresses/_form.html.erb where line #1 raised:

undefined local variable or method `address_type' for #<#Class:0x007ff32fc3a030:0x007ff323997410>

Extracted source (around line #1):

1: <% country_id = address_type == 'billing' ? 'bcountry' : 'scountry' %>
2: <% ADDRESS_FIELDS.each do |field| %>
3:   <% if field == "country" %>
4:     <p class="field" id="<%= country_id %>">

I already have spree_address_book version 1.2.0. Is that the reason why it crashs? Can I update the version to 1.2.3?
