### ISSUE TITLE
undefined method `addresses' for #<Spree::User:0x007fff08e7b210>

### ISSUE THREAD

**Issue by tvdeyen** [spree-contrib/spree_address_book#14]
After updating to 1.0.1 I get this message.

`undefined method`addresses' for #Spree::User:0x007fff08e7b210`

```
activemodel (3.1.6) lib/active_model/attribute_methods.rb:385:in `method_missing'
activerecord (3.1.6) lib/active_record/attribute_methods.rb:60:in `method_missing'
app/views/spree/users/show.html.erb:54:in `_6965e791224c7a92a42ad654e628387d'
actionpack (3.1.6) lib/action_view/template.rb:144:in `block in render'
activesupport (3.1.6) lib/active_support/notifications.rb:55:in `instrument'
actionpack (3.1.6) lib/action_view/template.rb:142:in `render'
deface (0.9.1) lib/deface/action_view_extensions.rb:37:in `render'
actionpack (3.1.6) lib/action_view/renderer/template_renderer.rb:40:in `block (2 levels) in render_template'
actionpack (3.1.6) lib/action_view/renderer/abstract_renderer.rb:33:in `block in instrument'
activesupport (3.1.6) lib/active_support/notifications.rb:53:in `block in instrument'
activesupport (3.1.6) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (3.1.6) lib/active_support/notifications.rb:53:in `instrument'
actionpack (3.1.6) lib/action_view/renderer/abstract_renderer.rb:33:in `instrument'
actionpack (3.1.6) lib/action_view/renderer/template_renderer.rb:39:in `block in render_template'
actionpack (3.1.6) lib/action_view/renderer/template_renderer.rb:47:in `render_with_layout'
actionpack (3.1.6) lib/action_view/renderer/template_renderer.rb:38:in `render_template'
actionpack (3.1.6) lib/action_view/renderer/template_renderer.rb:12:in `block in render'
actionpack (3.1.6) lib/action_view/renderer/abstract_renderer.rb:22:in `wrap_formats'
actionpack (3.1.6) lib/action_view/renderer/template_renderer.rb:9:in `render'
actionpack (3.1.6) lib/action_view/renderer/renderer.rb:36:in `render_template'
actionpack (3.1.6) lib/action_view/renderer/renderer.rb:17:in `render'
actionpack (3.1.6) lib/abstract_controller/rendering.rb:120:in `_render_template'
actionpack (3.1.6) lib/action_controller/metal/streaming.rb:250:in `_render_template'
actionpack (3.1.6) lib/abstract_controller/rendering.rb:114:in `render_to_body'
actionpack (3.1.6) lib/action_controller/metal/renderers.rb:30:in `render_to_body'
actionpack (3.1.6) lib/action_controller/metal/compatibility.rb:43:in `render_to_body'
actionpack (3.1.6) lib/abstract_controller/rendering.rb:99:in `render'
actionpack (3.1.6) lib/action_controller/metal/rendering.rb:16:in `render'
actionpack (3.1.6) lib/action_controller/metal/instrumentation.rb:40:in `block (2 levels) in render'
activesupport (3.1.6) lib/active_support/core_ext/benchmark.rb:5:in `block in ms'
/Users/tvd/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
activesupport (3.1.6) lib/active_support/core_ext/benchmark.rb:5:in `ms'
actionpack (3.1.6) lib/action_controller/metal/instrumentation.rb:40:in `block in render'
actionpack (3.1.6) lib/action_controller/metal/instrumentation.rb:78:in `cleanup_view_runtime'
activerecord (3.1.6) lib/active_record/railties/controller_runtime.rb:24:in `cleanup_view_runtime'
actionpack (3.1.6) lib/action_controller/metal/instrumentation.rb:39:in `render'
actionpack (3.1.6) lib/action_controller/metal/implicit_render.rb:10:in `default_render'
actionpack (3.1.6) lib/action_controller/metal/implicit_render.rb:5:in `send_action'
actionpack (3.1.6) lib/abstract_controller/base.rb:167:in `process_action'
actionpack (3.1.6) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (3.1.6) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
activesupport (3.1.6) lib/active_support/callbacks.rb:479:in `_run__1366725006079183838__process_action__3689800999998951312__callbacks'
activesupport (3.1.6) lib/active_support/callbacks.rb:386:in `_run_process_action_callbacks'
activesupport (3.1.6) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (3.1.6) lib/abstract_controller/callbacks.rb:17:in `process_action'
actionpack (3.1.6) lib/action_controller/metal/rescue.rb:17:in `process_action'
actionpack (3.1.6) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
activesupport (3.1.6) lib/active_support/notifications.rb:53:in `block in instrument'
activesupport (3.1.6) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (3.1.6) lib/active_support/notifications.rb:53:in `instrument'
actionpack (3.1.6) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
actionpack (3.1.6) lib/action_controller/metal/params_wrapper.rb:201:in `process_action'
activerecord (3.1.6) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (3.1.6) lib/abstract_controller/base.rb:121:in `process'
actionpack (3.1.6) lib/abstract_controller/rendering.rb:45:in `process'
actionpack (3.1.6) lib/action_controller/metal.rb:193:in `dispatch'
actionpack (3.1.6) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
actionpack (3.1.6) lib/action_controller/metal.rb:236:in `block in action'
actionpack (3.1.6) lib/action_dispatch/routing/route_set.rb:71:in `call'
actionpack (3.1.6) lib/action_dispatch/routing/route_set.rb:71:in `dispatch'
actionpack (3.1.6) lib/action_dispatch/routing/route_set.rb:35:in `call'
rack-mount (0.8.3) lib/rack/mount/route_set.rb:152:in `block in call'
rack-mount (0.8.3) lib/rack/mount/code_generation.rb:96:in `block in recognize'
rack-mount (0.8.3) lib/rack/mount/code_generation.rb:68:in `optimized_each'
rack-mount (0.8.3) lib/rack/mount/code_generation.rb:95:in `recognize'
rack-mount (0.8.3) lib/rack/mount/route_set.rb:141:in `call'
actionpack (3.1.6) lib/action_dispatch/routing/route_set.rb:538:in `call'
/Users/tvd/.rvm/gems/ruby-1.9.3-p194/bundler/gems/spree-5886b55cbf8d/core/lib/spree/core/middleware/redirect_legacy_product_url.rb:13:in `call'
/Users/tvd/.rvm/gems/ruby-1.9.3-p194/bundler/gems/spree-5886b55cbf8d/core/lib/spree/core/middleware/seo_assist.rb:27:in `call'
railties (3.1.6) lib/rails/engine.rb:456:in `call'
railties (3.1.6) lib/rails/railtie/configurable.rb:30:in `method_missing'
rack-mount (0.8.3) lib/rack/mount/prefix.rb:26:in `call'
rack-mount (0.8.3) lib/rack/mount/route_set.rb:152:in `block in call'
rack-mount (0.8.3) lib/rack/mount/code_generation.rb:96:in `block in recognize'
rack-mount (0.8.3) lib/rack/mount/code_generation.rb:89:in `optimized_each'
rack-mount (0.8.3) lib/rack/mount/code_generation.rb:95:in `recognize'
rack-mount (0.8.3) lib/rack/mount/route_set.rb:141:in `call'
actionpack (3.1.6) lib/action_dispatch/routing/route_set.rb:538:in `call'
warden (1.0.6) lib/warden/manager.rb:35:in `block in call'
warden (1.0.6) lib/warden/manager.rb:34:in `catch'
warden (1.0.6) lib/warden/manager.rb:34:in `call'
actionpack (3.1.6) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
rack (1.3.6) lib/rack/etag.rb:23:in `call'
rack (1.3.6) lib/rack/conditionalget.rb:25:in `call'
actionpack (3.1.6) lib/action_dispatch/middleware/head.rb:14:in `call'
actionpack (3.1.6) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
actionpack (3.1.6) lib/action_dispatch/middleware/flash.rb:243:in `call'
rack (1.3.6) lib/rack/session/abstract/id.rb:195:in `context'
rack (1.3.6) lib/rack/session/abstract/id.rb:190:in `call'
/Users/tvd/.rvm/gems/ruby-1.9.3-p194/bundler/gems/alchemy_cms-735bdd7f5b4d/lib/middleware/flash_session_cookie.rb:17:in `call'
actionpack (3.1.6) lib/action_dispatch/middleware/cookies.rb:331:in `call'
activerecord (3.1.6) lib/active_record/query_cache.rb:64:in `call'
activerecord (3.1.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:477:in `call'
actionpack (3.1.6) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (3.1.6) lib/active_support/callbacks.rb:392:in `_run_call_callbacks'
activesupport (3.1.6) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (3.1.6) lib/action_dispatch/middleware/callbacks.rb:28:in `call'
rails-dev-tweaks (0.6.1) lib/rails_dev_tweaks/granular_autoload/middleware.rb:34:in `call'
rack (1.3.6) lib/rack/sendfile.rb:101:in `call'
actionpack (3.1.6) lib/action_dispatch/middleware/remote_ip.rb:48:in `call'
actionpack (3.1.6) lib/action_dispatch/middleware/show_exceptions.rb:47:in `call'
railties (3.1.6) lib/rails/rack/logger.rb:13:in `call'
rack (1.3.6) lib/rack/methodoverride.rb:24:in `call'
rack (1.3.6) lib/rack/runtime.rb:17:in `call'
activesupport (3.1.6) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
rack (1.3.6) lib/rack/lock.rb:15:in `call'
actionpack (3.1.6) lib/action_dispatch/middleware/static.rb:61:in `call'
rack-cache (1.2) lib/rack/cache/context.rb:136:in `forward'
rack-cache (1.2) lib/rack/cache/context.rb:245:in `fetch'
rack-cache (1.2) lib/rack/cache/context.rb:185:in `lookup'
rack-cache (1.2) lib/rack/cache/context.rb:66:in `call!'
rack-cache (1.2) lib/rack/cache/context.rb:51:in `call'
railties (3.1.6) lib/rails/engine.rb:456:in `call'
railties (3.1.6) lib/rails/application.rb:143:in `call'
rack (1.3.6) lib/rack/content_length.rb:14:in `call'
railties (3.1.6) lib/rails/rack/log_tailer.rb:14:in `call'
rack (1.3.6) lib/rack/handler/webrick.rb:59:in `service'
/Users/tvd/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/webrick/httpserver.rb:138:in `service'
/Users/tvd/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run'
/Users/tvd/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/webrick/server.rb:191:in `block in start_thread'
```

Spree 1.0-stable
